# Generated by Django 4.2.11 on 2026-06-16 18:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('fleet_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('origin_hub', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Expected', 'Expected'), ('Arrived', 'Arrived'), ('Unloading', 'Unloading'), ('Reconciled', 'Reconciled')], default='Expected', max_length=50)),
                ('arrival_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fleets',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('zone', models.CharField(max_length=10)),
                ('rack', models.CharField(max_length=10)),
                ('shelf', models.CharField(max_length=10)),
                ('is_occupied', models.BooleanField(default=False)),
                ('weight_capacity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('total_boxes', models.IntegerField(default=1)),
                ('delivery_address', models.TextField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('route_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'routes',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('WarehouseStaff', 'Warehouse Staff'), ('Driver', 'Driver'), ('Manager', 'Manager')], max_length=50)),
                ('active_status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='ShipmentBox',
            fields=[
                ('tracking_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('box_sequence', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('In-Transit', 'In-Transit'), ('Unloaded', 'Unloaded'), ('Stored', 'Stored'), ('Retrieved', 'Retrieved'), ('Dispatched', 'Dispatched')], default='In-Transit', max_length=50)),
                ('unloaded_at', models.DateTimeField(blank=True, null=True)),
                ('stored_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('fleet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boxes', to='core.fleet')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boxes', to='core.location')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boxes', to='core.order')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boxes', to='core.route')),
            ],
            options={
                'db_table': 'shipment_boxes',
            },
        ),
        migrations.AddField(
            model_name='route',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='core.user'),
        ),
        migrations.CreateModel(
            name='PostalCodeMapping',
            fields=[
                ('postal_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postal_codes', to='core.route')),
            ],
            options={
                'db_table': 'postal_code_mapping',
            },
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(condition=models.Q(('is_occupied', False)), fields=['zone', 'rack', 'shelf'], name='idx_open_locations'),
        ),
        migrations.AddIndex(
            model_name='shipmentbox',
            index=models.Index(fields=['status'], name='idx_boxes_status'),
        ),
    ]
