# Generated by Django 4.2.11 on 2026-06-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentbox',
            name='retrieved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
